version: '3'

services:
  # Vulnerable web application for practicing web attacks
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8080:80"
    networks:
      pentest_network:
        ipv4_address: 172.20.0.2

  # Metasploitable 2 - Intentionally vulnerable Linux machine
  metasploitable:
    image: tleemcjr/metasploitable2
    container_name: metasploitable
    ports:
      - "20:20"
      - "21:21"
      - "22:22"
      - "23:23"
      - "25:25"
      - "80:80"
      - "139:139"
      - "445:445"
      - "3306:3306"
      - "5432:5432"
      - "8180:8180"
    networks:
      pentest_network:
        ipv4_address: 172.20.0.3
    tty: true

  # Kali Linux for penetration testing
  kali:
    image: kalilinux/kali-rolling
    container_name: kali
    volumes:
      - ./kali_data:/root/data
    ports:
      - "2222:22"
    networks:
      pentest_network:
        ipv4_address: 172.20.0.4
    tty: true
    command: bash -c "apt-get update && apt-get install -y openssh-server nmap metasploit-framework && service ssh start && tail -f /dev/null"

networks:
  pentest_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
